version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      python-deps:
        applies-to: version-updates
        patterns:
          - "*"
      python-security:
        applies-to: security-updates
        patterns:
          - "*"
